### ISSUE TITLE
Change the timer duration

### ISSUE THREAD

**Issue by leonardomteixeira** [MuhammadUsamaSiddiqui/circular_countdown_timer#12]
**Good night,** 
I'm making a pomodoro app and I'm having trouble changing the timer duration value. It reads only the first set value. **Thank you ;)**

**Comment by MuhammadUsamaSiddiqui** [comment]
There is already optional **int** parameter in `restart` method of `CountDownController` to easily achieve your requirement
**i.e** `_controller.restart (duration: 20);`

In the above statement, the named parameter `duration` is updated duration for countdown.
