### ISSUE TITLE
Feature Request : Countdown Text Format

### ISSUE THREAD

**Issue by nivisi** [MuhammadUsamaSiddiqui/circular_countdown_timer#13]
Hey!

It would be great to provide a possibility to change the countdown text format. For example, my app requires just a number of seconds to display rather than a `0:04` etc.

I can implement it if you don't mind.

**Comment by MuhammadUsamaSiddiqui** [comment]
Hi! I have added an optional String parameter named `textFormat` in `CircularCountDownTimer` to format countdown text. You can assign value to it using `CountdownTextFormat` class. For now `CountdownTextFormat` has three formats:

1) **HH_MM_SS** : resulted String will be in `HH:mm:ss` format.
2) **MM_SS** : resulted String will be in `mm:ss` format.
3) **SS** : resulted String will be in `ss` format.

If you don't provide value to `textFormat` parameter then the format will be **default**.

A **default** format is `HH:mm:ss` but:
  - If hours value is zero, then default format will be automatically converted into `mm:ss`.
  - If minutes value is zero, then default format will be automatically converted into `ss`.

**Comment by nivisi** [comment]
Nice, thanks!
