### ISSUE TITLE
Feature Request: Control the start of countdown

### ISSUE THREAD

**Issue by repsajanboy** [MuhammadUsamaSiddiqui/circular_countdown_timer#14]
Hi I been wondering if how can I control the start of countdown for example I wish to click a button first before starting countdown, is it possible? Thank you so much! Very nice package.

**Comment by MuhammadUsamaSiddiqui** [comment]
Hi! I have added an optional bool parameter named `autoStart` in `CircularCountDownTimer` to control start of countdown timer. If you want to start timer then you have to call `start` method on `CountDownController` object.

**Comment by repsajanboy** [comment]
Thank you so much!
