### ISSUE TITLE
missing Key for CircularCountDownTimer Widget + support to control if to disaply hours instead of minuts

### ISSUE THREAD

**Issue by kw2019ltd** [MuhammadUsamaSiddiqui/circular_countdown_timer#2]
hi
pls enhance CircularCountDownTimer and add Key to constructor.

+

if possible in case duration is more than 1 hour to support display by hour and not min , it possible to introduce flag to display in min or hours

**Comment by MuhammadUsamaSiddiqui** [comment]
1. Working on the first issue, trying to introduce new parameter named **controller**, which will act as a key and use to control the countdown.

2. Your second issue (Hour support in Countdown Text) has resolved.

**Comment by kw2019ltd** [comment]
Salam 3lekom shukran

**Comment by MuhammadUsamaSiddiqui** [comment]
Added **Key** named **key**. You can find it in latest version of Circular Countdown Timer.
