### ISSUE TITLE
Feature Request: Add onChange event

### ISSUE THREAD

**Issue by aleffabricio** [MuhammadUsamaSiddiqui/circular_countdown_timer#22]
Hi how are you? how to add onChange functionality to return the current second /minute/hour? it would be good because it would help trigger other events according to the current time shown.

**Comment by bksubhuti** [comment]
yes.. good request.. mine too.  nice control though.  I have to use the stopwatch one until this is added.

**Comment by MuhammadUsamaSiddiqui** [comment]
Done, Added.
