### ISSUE TITLE
Feature Request: Show duration value when autoStart is false

### ISSUE THREAD

**Issue by aleffabricio** [MuhammadUsamaSiddiqui/circular_countdown_timer#23]
When the autoStart is false instead of showing the initial value 00:00 for example it could start showing the time I spent in the duration.

**Comment by pdaether** [comment]
I can double that. If `isReverse` is `true`, I would also expect that the Widget shows the duration value if  `autoStart` is `false`.

**Comment by ScottishRoss** [comment]
Ditto.

**Comment by MuhammadUsamaSiddiqui** [comment]
Fixed.
