### ISSUE TITLE
Option to reset countdown timer

### ISSUE THREAD

**Issue by andreasgrossmann** [MuhammadUsamaSiddiqui/circular_countdown_timer#34]
How about a CountDownController method to reset the countdown timer?

**Comment by mcradha** [comment]
I am also looking for the same, Right now we have an option to restart. However, I have a situation where at the end of the level 1, I need to just reset the timer to the duration for Level 2. It will restart only after the user starts Level 2. However I am not able to make that happen with restart. As it restarts the timer, even before the user has started the new level.

**Comment by MuhammadUsamaSiddiqui** [comment]
I have added a `reset` method in CountDownController. You can use it like this:

```
CountDownController _controller = CountDownController();
_controller.reset();
```
