### ISSUE TITLE
[Honer Device] time run very fast and 180 minute take less than minute to end ??

### ISSUE THREAD

**Issue by Joseph-Nathan** [MuhammadUsamaSiddiqui/circular_countdown_timer#37]
2 user have this problem and have Honer devices .
the time run vary fast like ,it's have mad speedup ?

please help .

**Comment by gorkemg0** [comment]
Did you find a solution? I'm having this problem too. I rarely have this problem with my users.

**Comment by muziyuqi** [comment]
https://github.com/flutter/flutter/issues/60917#issuecomment-654378296
