### ISSUE TITLE
State fields does not aligned with the state of the timer

### ISSUE THREAD

**Issue by eitand** [MuhammadUsamaSiddiqui/circular_countdown_timer#41]
timerController.isPaused  // result = false
timerController.pause()
timerController.isPaused  // result = true
timerController.resume()
timerController.isPaused  // result = true

Same logic with isResumed

**Comment by MuhammadUsamaSiddiqui** [comment]
This issue has been fixed in `circular_countdown_timer: ^0.2.3`
