### ISSUE TITLE
New CountDownTextFormat added

### ISSUE THREAD

**Issue by cagdaspektas** [MuhammadUsamaSiddiqui/circular_countdown_timer#43]
Hi there i could not found hours, just min and day type for the code.So i changed package a little bit.
Here is the code that i change:
class CountdownTextFormat {
  static const String HH_MM_SS = "HH:mm:ss";
  static const String HH = "HH";
  static const String DD = "DD";
  static const String MM = "mm";
  static const String MM_SS = "mm:ss";
  static const String SS = "ss";
  static const String S = "s";
}
String _getTime(Duration duration) {
    // For HH:mm:ss format
    if (widget.textFormat == CountdownTextFormat.HH_MM_SS) {
      return '${duration.inHours.toString().padLeft(2, '0')}:${(duration.inMinutes % 60).toString().padLeft(2, '0')}:${(duration.inSeconds % 60).toString().padLeft(2, '0')}';
    }
    // For mm:ss format
    else if (widget.textFormat == CountdownTextFormat.MM_SS) {
      return '${(duration.inMinutes % 60).toString().padLeft(2, '0')}:${(duration.inSeconds % 60).toString().padLeft(2, '0')}';
    } else if (widget.textFormat == CountdownTextFormat.DD) {
      return '${(duration.inDays)}';
    } else if (widget.textFormat == CountdownTextFormat.HH) {
      return '${duration.inHours.toString().padLeft(2, '0')}';
    } else if (widget.textFormat == CountdownTextFormat.MM) {
      return '${(duration.inMinutes % 60).toString().padLeft(2, '0')}';
    }
    // For ss format
    else if (widget.textFormat == CountdownTextFormat.SS) {
      return '${(duration.inSeconds).toString().padLeft(2, '0')}';
    }
    // For s format
    else if (widget.textFormat == CountdownTextFormat.S) {
      return '${(duration.inSeconds)}';
    } else {
      // Default format
      return _defaultFormat(duration);
    }
  }
if you want you can update the package.Thank you for your package it helps a lot.

**Comment by cagdaspektas** [comment]
@joshuadeguzman @MuhammadUsamaSiddiqui

**Comment by flawnn** [comment]
Please make a PR for this. We can not work with this unless you put in the work and time to actually make it compatible with the current changes 🤲 

Thanks a lot though!
