### ISSUE TITLE
Reverse countdown but not direction

### ISSUE THREAD

**Issue by DanielSjtea** [MuhammadUsamaSiddiqui/circular_countdown_timer#5]
Can the countdown timer be reversed (from Max to 0) but the direction not be reversed?
As in, when 'isReversed' is true, can the countdown timer continue to go in a clockwise direction (instead of the currently anti-clockwise direction).

**Comment by MuhammadUsamaSiddiqui** [comment]
I have added optional **bool** parameter named `isReverseAnimation` to handle Animation Direction i.e Forward or Reverse. If it's value is true then animation will be **Reverse** else animation will be **Forward**. You can check **READ ME** for further details.
