### ISSUE TITLE
Circular countdown timer restricted to 3.0.0 and does not support higher versions of flutter

### ISSUE THREAD

**Issue by goldenroses** [MuhammadUsamaSiddiqui/circular_countdown_timer#50]
Using flutter version `3.3.10` doesn't work on `circular_countdown_timer`. Getting the error below.

`Because circular_countdown_timer 0.2.3 requires Flutter SDK version >=1.17.0 and no versions of circular_countdown_timer match >0.2.3 <0.3.0, circular_countdown_timer ^0.2.3 is forbidden.
So, because yourProject depends on circular_countdown_timer ^0.2.3, version solving failed.`

Could the [environment sdk](https://github.com/MuhammadUsamaSiddiqui/circular_countdown_timer/blob/master/pubspec.yaml) be upgraded to support `3.3.10` ?

**Comment by MuhammadUsamaSiddiqui** [comment]
Hi everyone, I have released a new version **0.2.4** of the package on pub.dev after migrating it to the Flutter version 3.22.3
