### ISSUE TITLE
repo in development?

### ISSUE THREAD

**Issue by trashcoder** [MuhammadUsamaSiddiqui/circular_countdown_timer#62]
Hi @flawnn,

i have seen, that you merged some pull requests some two days ago. I thought this repo is dead because the last release was 2 years ago, so i forked it and added some features like reset without autostart and changing duration. I extracted the countdown Controller to a separate file, too.

My question is, will your repo be in development in the future, or should a go on with my fork?

Kind Regards
Trashcoder

**Comment by flawnn** [comment]
We will definitely update it. I am in talks with the maintainer of this repo, and I'll prep a release.

 Feel free to make PRs for all the stuff you added & I'll merge it! 🫶

**Comment by rsvo** [comment]
Hey @flawnn,
any update when there might be a release?
If I can help out somehow, please let me know. I'm happy to help.

**Comment by MuhammadUsamaSiddiqui** [comment]
Hi everyone, I have released a new version **0.2.4** of the package on pub.dev after migrating it to the Flutter version 3.22.3

**Comment by trashcoder** [comment]
Too bad it's not a feature upgrade.
